version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      POSTGRES_DB: production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U golang -d production"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  authorization-service:
    build: ./authorization-service
    container_name: authorization_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "user=golang password=golang host=postgres port=5432 dbname=production sslmode=disable"

  content-service:
    build: ./content-service
    container_name: content_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "user=golang password=golang host=postgres port=5432 dbname=production sslmode=disable"

  jisho-service:
    build: ./jisho-service
    container_name: jisho_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "user=golang password=golang host=postgres port=5432 dbname=production sslmode=disable"

  login-service:
    build: ./login-service
    container_name: login_service
    depends_on:
       postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "user=golang password=golang host=postgres port=5432 dbname=production sslmode=disable"

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - authorization-service
      - content-service
      - jisho-service
      - login-service
    ports:
      - "8080:8080"

volumes:
  postgres_data:
