events {
    worker_connections 1024;
}

# Uncomment for errors in terminal on localhost
# error_log /dev/stdout info;

http {
    # Uncomment for logs in terminal on localhost
    # access_log /dev/stdout;
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 8080;

        location / {
            return 404;
        }

        location ~ ^/jisho-service/(.*)$ {
            include cors.conf;
            set $jisho http://jisho_service:8080;
            proxy_pass $jisho/$1$is_args$args;
        }

        location ~ ^/content-service/(.*)$ {
            include cors.conf;
            set $content http://content_service:8080;
            proxy_pass $content/$1$is_args$args;
        }

        location ~ ^/idp-service/(.*)$ {
            include cors.conf;
            set $idp http://idp_service:8080;
            proxy_pass $idp/$1$is_args$args;
        }

        location /health {
            return 200;
        }
    }
}