events {
    worker_connections 1024;
}

# Uncomment for errors in terminal on localhost
# error_log /dev/stdout info;

http {
    # Uncomment for logs in terminal on localhost
    # access_log /dev/stdout;

    # Global CORS configuration
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
    add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;

    # Handle preflight requests globally
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
        add_header 'Access-Control-Max-Age' 1728000;
        return 204;
    }

    server {
        listen 8080;
        server_name teun-stout.com www.teun-stout.com 192.168.178.57;

        location /jisho-service/ {
            proxy_pass http://jisho_service:8080/;
        }

        location /login-service/ {
            proxy_pass http://login_service:8080/;
        }

        location /content-service/ {
            proxy_pass http://content_service:8080/;
        }

        location /authorization-service/ {
            proxy_pass http://authorization_service:9096/;
        }

        location /health {
            return 200;
        }
    }
}